---
galaxy_info:
  role_name: automation_logger
  author: EDA Team
  description: Reusable role for logging automation execution to Snowflake
  company: Ensono
  version: "1.0.0"
  
  license: Internal
  
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
  
  galaxy_tags:
    - logging
    - automation
    - snowflake
    - monitoring

dependencies: []
